#!/bin/sh
#
# bughunter service which runs django bughunter web application
### BEGIN INIT INFO
# Provides: bughunter
# Required-Start: mysqld
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: The bughunter django web application
# Description:      The bughunter django web application
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/mozilla/builds/hg.mozilla.org/sisyphus/python/sisyphus/webapp/service/bin/bughunter"
prog=${exec##*/}

#config="<path to major config file>"

umask 0002

if [[ ! -d /var/log/bughunter ]]; then
   mkdir /var/log/bughunter
   chown bughunter:bughunter /var/log/bughunter
fi

if [[ ! -d /var/run/bughunter ]]; then
   mkdir /var/run/bughunter
   chown bughunter:bughunter /var/run/bughunter
fi

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    #[ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon --user bughunter $exec
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    # stop it here, often "killproc $prog"
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
